// <auto-generated />
using Hack24_2018_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Hack242018API.Migrations
{
    [DbContext(typeof(EcoNottsDbContext))]
    [Migration("20180310230326_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hack24_2018_API.Models.Establishment", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("BusinessName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("Hack24_2018_API.Models.Reports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EstablishmentId");

                    b.Property<int>("UsesStraws");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Hack24_2018_API.Models.Reports", b =>
                {
                    b.HasOne("Hack24_2018_API.Models.Establishment", "Establishment")
                        .WithMany("Reports")
                        .HasForeignKey("EstablishmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
